// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Valoron.Activities.Infrastructure.Persistence;

#nullable disable

namespace Valoron.Activities.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ActivitiesDbContext))]
    partial class ActivitiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("activities")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Valoron.Activities.Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Activities", "activities");
                });

            modelBuilder.Entity("Valoron.Activities.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books", "activities");
                });

            modelBuilder.Entity("Valoron.Activities.Domain.Activity", b =>
                {
                    b.OwnsOne("Valoron.Activities.Domain.ActivityCategory", "Category", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Category_Code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Category_Name");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities", "activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("Valoron.Activities.Domain.ActivityDifficulty", "Difficulty", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Difficulty_Value");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities", "activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("Valoron.Activities.Domain.ActivityMeasurement", "Measurement", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CurrentValue")
                                .HasColumnType("numeric")
                                .HasColumnName("Measurement_Current");

                            b1.Property<decimal>("TargetValue")
                                .HasColumnType("numeric")
                                .HasColumnName("Measurement_Target");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("Measurement_Unit");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities", "activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Difficulty")
                        .IsRequired();

                    b.Navigation("Measurement")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
